# Generated by Django 4.2.7 on 2023-11-10 18:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0002_cliente_compra_consola_entrada_historicoprecios_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="compra",
            name="id_cliente",
        ),
        migrations.RemoveField(
            model_name="compra",
            name="id_producto",
        ),
        migrations.RemoveField(
            model_name="consola",
            name="juegos_instalados",
        ),
        migrations.RemoveField(
            model_name="sesion",
            name="id_cliente",
        ),
        migrations.RemoveField(
            model_name="sesion",
            name="id_consola",
        ),
        migrations.DeleteModel(
            name="Cliente",
        ),
        migrations.DeleteModel(
            name="Compra",
        ),
        migrations.DeleteModel(
            name="Consola",
        ),
        migrations.DeleteModel(
            name="Juego",
        ),
        migrations.DeleteModel(
            name="Sesion",
        ),
    ]
