# Generated by Django 4.2.7 on 2023-11-10 19:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "Inventario",
            "0003_remove_compra_id_cliente_remove_compra_id_producto_and_more",
        ),
    ]

    operations = [
        migrations.RenameField(
            model_name="producto",
            old_name="precio",
            new_name="precio_venta",
        ),
        migrations.AddField(
            model_name="entrada",
            name="cant_comprada",
            field=models.IntegerField(
                default=0, validators=[django.core.validators.MinValueValidator(0)]
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="producto",
            name="cant_invent",
            field=models.IntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
