# Generated by Django 4.2.7 on 2023-11-10 19:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Inventario", "0004_rename_precio_producto_precio_venta_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="entrada",
            old_name="cant_comprada",
            new_name="cant_ingresada",
        ),
        migrations.AlterField(
            model_name="entrada",
            name="proveedor",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="f_actualizacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="producto",
            name="precio_venta",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=8,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
