# Generated by Django 4.2.7 on 2023-11-30 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0003_remove_ropa_tipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='clave_acceso',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
