# Generated by Django 4.2.7 on 2023-12-01 23:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0005_alter_ropa_genero'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usuario',
            old_name='id_pais',
            new_name='id_ciudad',
        ),
    ]
