# Generated by Django 4.2.7 on 2023-12-06 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tienda', '0006_rename_id_pais_usuario_id_ciudad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='factura',
            name='f_facturacion',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='usuario',
            name='preferencias',
            field=models.ManyToManyField(blank=True, null=True, to='Tienda.categoria'),
        ),
    ]
