# Generated by Django 4.2.7 on 2023-11-10 18:26

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "Inventario",
            "0003_remove_compra_id_cliente_remove_compra_id_producto_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Cliente",
            fields=[
                ("ci", models.PositiveIntegerField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=30)),
                ("apellido", models.CharField(max_length=30)),
                (
                    "genero",
                    models.CharField(
                        choices=[("masculino", "Masculino"), ("femenino", "Femenino")],
                        max_length=10,
                    ),
                ),
                ("f_nacimiento", models.DateField()),
                ("ubicacion", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=15)),
                ("correo", models.EmailField(max_length=50, unique=True)),
                ("f_creacion", models.DateField(auto_now_add=True)),
                ("f_actualizacion", models.DateField(null=True)),
            ],
            options={
                "verbose_name": "Cliente",
                "verbose_name_plural": "Clientes",
                "ordering": ["-f_creacion"],
            },
        ),
        migrations.CreateModel(
            name="Consola",
            fields=[
                (
                    "numero",
                    models.PositiveIntegerField(primary_key=True, serialize=False),
                ),
                ("cant_controles", models.PositiveIntegerField()),
                ("serial", models.CharField(max_length=30, null=True)),
            ],
            options={
                "verbose_name": "Consola",
                "verbose_name_plural": "Consolas",
            },
        ),
        migrations.CreateModel(
            name="Juego",
            fields=[
                (
                    "id",
                    models.CharField(max_length=20, primary_key=True, serialize=False),
                ),
                ("nombre", models.CharField(max_length=30)),
                ("f_compra", models.DateField()),
                ("generos", models.CharField(max_length=50)),
                ("precio_compra", models.DecimalField(decimal_places=2, max_digits=8)),
                ("cantidad", models.PositiveIntegerField()),
                (
                    "tipo",
                    models.CharField(
                        choices=[
                            ("accion", "Acción"),
                            ("aventura", "Aventura"),
                            ("deportes", "Deportes"),
                            ("estrategia", "Estrategia"),
                            ("otros", "Otros"),
                        ],
                        max_length=20,
                    ),
                ),
                ("empresa", models.CharField(max_length=50)),
            ],
            options={
                "verbose_name": "Juego",
                "verbose_name_plural": "Juegos",
            },
        ),
        migrations.CreateModel(
            name="Sesion",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("fh_inicio", models.DateTimeField()),
                ("fh_final", models.DateTimeField()),
                (
                    "met_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=15,
                    ),
                ),
                ("cant_horas", models.DecimalField(decimal_places=1, max_digits=5)),
                ("cant_personas", models.PositiveIntegerField()),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Local.cliente"
                    ),
                ),
                (
                    "id_consola",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Local.consola"
                    ),
                ),
            ],
            options={
                "verbose_name": "Sesion",
                "verbose_name_plural": "Sesiones",
            },
        ),
        migrations.AddField(
            model_name="consola",
            name="juegos_instalados",
            field=models.ManyToManyField(to="Local.juego"),
        ),
        migrations.CreateModel(
            name="Compra",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "met_pago",
                    models.CharField(
                        choices=[
                            ("efectivo", "Efectivo"),
                            ("tarjeta", "Tarjeta"),
                            ("transferencia", "Transferencia"),
                        ],
                        max_length=15,
                    ),
                ),
                ("fh_compra", models.DateTimeField(auto_now_add=True)),
                (
                    "cantidad",
                    models.IntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "monto",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=8,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "id_cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="Local.cliente"
                    ),
                ),
                (
                    "id_producto",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="Inventario.producto",
                    ),
                ),
            ],
            options={
                "verbose_name": "Compra",
                "verbose_name_plural": "Compras",
                "ordering": ["-fh_compra"],
            },
        ),
    ]
