# Generated by Django 4.2.7 on 2023-11-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Local", "0002_alter_compra_cantidad_alter_juego_precio_compra"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="juego",
            name="empresa",
        ),
        migrations.AlterField(
            model_name="cliente",
            name="f_actualizacion",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="compra",
            name="met_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("pago_movil", "Pago Móvil"),
                ],
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="consola",
            name="serial",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="met_pago",
            field=models.CharField(
                choices=[
                    ("efectivo", "Efectivo"),
                    ("tarjeta", "Tarjeta"),
                    ("pago_movil", "Pago Móvil"),
                ],
                max_length=15,
            ),
        ),
    ]
