# Generated by Django 4.2.7 on 2023-11-10 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Local", "0003_remove_juego_empresa_alter_cliente_f_actualizacion_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="juego",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
