# Generated by Django 4.2.7 on 2023-11-10 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Local", "0004_alter_juego_id"),
    ]

    operations = [
        migrations.RenameField(
            model_name="juego",
            old_name="tipo",
            new_name="genero",
        ),
        migrations.RemoveField(
            model_name="juego",
            name="generos",
        ),
    ]
