# Generated by Django 4.2.7 on 2023-11-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Local", "0005_rename_tipo_juego_genero_remove_juego_generos"),
    ]

    operations = [
        migrations.AddField(
            model_name="consola",
            name="f_actualizacion",
            field=models.DateField(blank=True, null=True),
        ),
    ]
