# Generated by Django 4.2.7 on 2023-11-10 20:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Local", "0006_consola_f_actualizacion"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sesion",
            name="cant_horas",
            field=models.DecimalField(
                decimal_places=1,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AlterField(
            model_name="sesion",
            name="cant_personas",
            field=models.PositiveIntegerField(
                validators=[django.core.validators.MinValueValidator(0)]
            ),
        ),
    ]
