# Generated by Django 4.2.7 on 2023-11-10 20:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("Local", "0007_alter_sesion_cant_horas_alter_sesion_cant_personas"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="sesion",
            name="fh_final",
        ),
        migrations.RemoveField(
            model_name="sesion",
            name="fh_inicio",
        ),
        migrations.AddField(
            model_name="sesion",
            name="f_sesion",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sesion",
            name="h_final",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sesion",
            name="h_inicio",
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="juego",
            name="f_compra",
            field=models.DateField(auto_now_add=True),
        ),
    ]
